### ISSUE TITLE
Add geckodriver binary

### ISSUE THREAD

**Issue by alex-fournier** [spunjs/selenium-binaries#15]
I recently switched to Marionette for my selenium tests on Firefox. I therefore use [geckodriver](https://github.com/mozilla/geckodriver) and having this driver in selenium-binaries would allow me to keep all my binaries outside my repo.

**Comment by jsdevel** [comment]
Feel free to add it if you're able to @alex-fournier !

**Comment by alex-fournier** [comment]
I could do it but I was waiting for PR #13 to be merged. Can you accept it or close it so that I can start working on a stable codebase?

**Comment by jsdevel** [comment]
@alex-fournier I closed #13 due to staleness.  Feel free to add the geckodriver binary to this build.
