### ISSUE TITLE
Could not find C:\web\g07\node_modules\selenium-binaries\binary-paths.json

### ISSUE THREAD

**Issue by totty90** [spunjs/selenium-binaries#2]
From webdriver-sync https://github.com/jsdevel/webdriver-sync/issues/91
on win 7 32bit

**Comment by totty90** [comment]
The problem is in your async script:

    if(!iedriver){
      rStream = fs.createReadStream(resolve(ieConfig.binary.path, ieConfig.download.name));
      rStream
        .pipe(unzip.Parse())
        .on('entry', function(entry){
          if(entry.type === 'File'){
            entry.pipe(fs.createWriteStream(
              resolve(ieConfig.binary.path, entry.path),
              {mode:EXEC_MODE}
             ));
          }
        })
        .on('error', function(err){
          cb(err);
        })
        .on('close', function(){
          iedriver = resolve(ieConfig.binary.path, ieConfig.binary.name);
          cb();
        });
    }

There is no `cb()` if iedriver is true. Here is the fixed script

  tasks.push(function unzipIEDriver(cb){
    var rStream;
    if(!iedriver){
      rStream = fs.createReadStream(resolve(ieConfig.binary.path, ieConfig.download.name));
      rStream
        .pipe(unzip.Parse())
        .on('entry', function(entry){
          if(entry.type === 'File'){
            entry.pipe(fs.createWriteStream(
              resolve(ieConfig.binary.path, entry.path),
              {mode:EXEC_MODE}
             ));
          }
        })
        .on('error', function(err){
          cb(err);
        })
        .on('close', function(){
          iedriver = resolve(ieConfig.binary.path, ieConfig.binary.name);
          cb();
        });
    }else{
        cb();
    }
  });

**Comment by totty90** [comment]
I will pull request now

**Comment by jsdevel** [comment]
Thanks!  I'll get webdriver-sync updated as well.

**Comment by jsdevel** [comment]
closed by #91
