### ISSUE TITLE
chromedriver version 2.23+ cannot be downloaded for mac

### ISSUE THREAD

**Issue by ethnar** [spunjs/selenium-binaries#20]
With the current config.js it's not possible to load chromedriver version 2.23 and upwards (latest 2.24) on mac.

The problem is that google changed the dist to 64bit (only) and config.js has a hardcoded value for macs to use 32 bits.

**Comment by jsdevel** [comment]
PRs are welcome @ethnar !

**Comment by ethnar** [comment]
Created a PR that addressed the issue.

**Comment by ethnar** [comment]
Fixed in f5a3dbf41c39f1166cb10e3dd9b0416f2a368e9f

**Comment by ethnar** [comment]
Are there any plans on publishing the latest version in npm repository?

**Comment by ethnar** [comment]
Are there any plans on publishing the latest version in npm repository?

**Comment by ethnar** [comment]
Are there any plans on publishing the latest version in npm repository?

**Comment by ethnar** [comment]
Are there any plans on publishing the latest version in npm repository?

**Comment by ethnar** [comment]
Are there any plans on publishing the latest version in npm repository?

**Comment by ethnar** [comment]
Are there any plans on publishing the latest version in npm repository?

**Comment by ethnar** [comment]
Are there any plans on publishing the latest version in npm repository?

**Comment by ethnar** [comment]
Are there any plans on publishing the latest version in npm repository?

**Comment by ethnar** [comment]
Are there any plans on publishing the latest version in npm repository?

**Comment by ethnar** [comment]
Are there any plans on publishing the latest version in npm repository?

**Comment by ethnar** [comment]
Are there any plans on publishing the latest version in npm repository?

**Comment by ethnar** [comment]
Are there any plans on publishing the latest version in npm repository?

**Comment by ethnar** [comment]
Are there any plans on publishing the latest version in npm repository?

**Comment by jsdevel** [comment]
No worries about spam!  I can publish tonight.

**Comment by ethnar** [comment]
It'd be great, we could really user that release.

Kind regards
Arek
