### ISSUE TITLE
Remove last-config.json from npm package

### ISSUE THREAD

**Issue by timonag** [spunjs/selenium-binaries#28]
The [current distribution](https://registry.npmjs.org/selenium-binaries/-/selenium-binaries-0.13.0.tgz) contains @alex-fournier 's config. It means that postinstall hook always downloads binaries ignoring cached jars.
Please, republish a new version of the module on the npm registry without this file.

**Comment by alex-fournier** [comment]
You're right, I'm going to fix this right now.

**Comment by alex-fournier** [comment]
Fixed in `v0.13.1`, sorry for the inconvenience, there was an outdated `.npmignore` overriding the `.gitignore`.
