### ISSUE TITLE
No longer works on Node 11

### ISSUE THREAD

**Issue by boxfoot** [spunjs/selenium-binaries#29]
This library seems to not work any more on node 11.  AFAICT, this is because of the dependency on `unzip`, which (eventually) depends on `natives` which isn't working on Node 11.

I wanted to send a PR to fix this, but have been running into issues.  First I tried the `unzipper` library which is a drop-in replacement for `unzip`, but it's choking on the specific zip files returned here.  Then I tried `unzip2` but it has the same problems as `unzip`.

The best unzip option seems to be `yauzl` but that library does not provide an API to consume streams, which is leading to a more substantial rewrite than I was hoping for.  Curious if you've run into this yet and if you have other suggestions on a fix.

**Comment by NickTulett** [comment]
Fixed in 0.13.9
