### ISSUE TITLE
Chrome not reachable

### ISSUE THREAD

**Issue by tandrewnichols** [spunjs/selenium-binaries#4]
Hey, trying to use this in conjunction with webdriver-sync on travis, but when webdriver-sync tries to create the Chrome instance (using ChromeDriverService.build) I get "chrome not reachable." Is that something with the version of chromedriver being downloaded or where it is being placed or something else? I realize this may not be related to this library, but I'm looking for ideas on how to fix this.

**Comment by jsdevel** [comment]
travis doesn't actually have chrome installed.  you'll have to set that up independently.  See https://github.com/jsdevel/webdriver-sync/blob/master/.travis.yml#L4

**Comment by tandrewnichols** [comment]
Yeah, I am.

**Comment by jsdevel** [comment]
I've found them to be necessary on travis :cry:

**Comment by tandrewnichols** [comment]
Ok, I'll experiment more tomorrow. Thanks!
