### ISSUE TITLE
Cannot choose the IE webdriver version

### ISSUE THREAD

**Issue by jbdoumenjou** [spunjs/selenium-binaries#8]
The ie x64 driver could have a very very slow typing, one easy solution is to choose the x32 driver instead of the x64 (https://code.google.com/p/selenium/issues/detail?id=5116).
The driver is downloaded depending the architecture, could it be possible to add this choice in the configuration ?

**Comment by jsdevel** [comment]
Hmm, I think so.  We sould need to add a config file or something, but that should be doable.

**Comment by alex-fournier** [comment]
I also use the x32 driver for IE so it would be a useful feature.

**Comment by jsdevel** [comment]
please make this change if you can @jbdoumenjou.
